name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5433:5432
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: auth_test
        options: >-
          --health-cmd "pg_isready -U postgres" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install tools
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.34.1
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.4.0

      - name: Setup env
        run: |
          echo "HTTP_PORT=8080" >> $GITHUB_ENV
          echo "GRPC_PORT=9090" >> $GITHUB_ENV
          echo "DB_HOST=localhost" >> $GITHUB_ENV
          echo "DB_PORT=5433" >> $GITHUB_ENV
          echo "DB_USER=postgres" >> $GITHUB_ENV
          echo "DB_PASSWORD=password" >> $GITHUB_ENV
          echo "DB_NAME=auth_test" >> $GITHUB_ENV
          echo "DB_SSLMODE=disable" >> $GITHUB_ENV
          echo "JWT_SECRET_KEY=test-ci-secret" >> $GITHUB_ENV
          echo "JWT_ACCESS_TOKEN_DURATION=15" >> $GITHUB_ENV
          echo "JWT_REFRESH_TOKEN_DURATION=168" >> $GITHUB_ENV

      - name: Verify build
        run: go build ./...

      - name: Run unit and contract tests
        run: |
          go test ./tests/domain -v
          go test ./tests/contracts -v

      - name: Run integration tests
        env:
          DB_HOST: localhost
          DB_PORT: 5433
          DB_USER: postgres
          DB_PASSWORD: password
          DB_NAME: auth_test
          DB_SSLMODE: disable
          JWT_SECRET_KEY: test-ci-secret
          JWT_ACCESS_TOKEN_DURATION: 15
          JWT_REFRESH_TOKEN_DURATION: 168
        run: |
          go test -tags=integration ./tests/integration/tests/repository_tests -v
          go test -tags=integration ./tests/integration/tests/auth_handler_tests -v
          go test -tags=integration ./tests/integration/tests/auth_http_tests -v
          go test -tags=integration ./tests/integration/tests/auth_grpc_tests -v
          go test -tags=integration ./tests/integration/tests/auth_e2e_tests -v